name: sample_generator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - dem_stitcher
  - ipykernel
  - numpy
  - rasterio
  - pyvista
  - matplotlib
  - pyproj
  - scipy
  - pyyaml
  - pip
  - pip:
    - windkit==1.0.2
    # Installs as 'terrain_mesh' (import terrain_mesh as tm)
    - git+https://github.com/souravsud/terrain_following_mesh_generator.git
    # Installs as 'abl_bc_generator' (from abl_bc_generator import ...)
    - git+https://github.com/souravsud/ABL_BC_generator.git
    # Installs as 'taskmanager' (from taskmanager import ...)
    - git+https://github.com/souravsud/taskManager.git
